Print
kostyantynHrytsyuk/hangman-op-21 pull request #3
Opened 2022-11-11 13:14 UTC by VikaProkhorova

print

2022-11-11 13:24 UTC, Vitaliypn requested changes
Перша помилка це те, якщо ви вде використовували цю букву то в вас вже мінується спроба, а в умові за це не знімали
<img width="751" alt="Знімок екрана 2022-11-11 о 15 24 16" src="https://user-images.githubusercontent.com/116552588/201349395-d229159d-7000-41ed-928f-83f433f8a7f0.png">

2022-11-11 13:28 UTC, Vitaliypn requested changes
Друга помилка полягає в тому, що коли гравець перемагає, то ви виводите None (варіант перемоги не прописаний), а в умові завдання маєте виводити 'Congratulations, you won!', так само і для поразки.
<img width="389" alt="Знімок екрана 2022-11-11 о 15 28 17" src="https://user-images.githubusercontent.com/116552588/201350024-16fd28d8-a402-4f90-9bd2-2366df54b2f6.png">
<img width="402" alt="Знімок екрана 2022-11-11 о 15 28 27" src="https://user-images.githubusercontent.com/116552588/201350026-32d1bc46-c8ab-48b4-813d-417edd101c7d.png">

2022-11-11 13:46 UTC, Vitaliypn requested changes
Функція в кінці всерівно вивидоть None, бо ви в кінці використовуєте print, краще буде використати return та забрати else
<img width="450" alt="Знімок екрана 2022-11-11 о 15 44 06" src="https://user-images.githubusercontent.com/116552588/201353185-02146a62-8470-476d-b24b-6848c6540fc1.png">
<img width="342" alt="Знімок екрана 2022-11-11 о 15 44 37" src="https://user-images.githubusercontent.com/116552588/201353195-99bd3504-9088-44bf-9627-68bf20d76b00.png">

2022-11-11 13:48 UTC, kostyantynHrytsyuk requested changes
Я не бачу де у коді виводиться поточний стан слова
Якщо я загадаю apple і введу літеру p

То програма мала б вивести _ p p _ _
Якщо це десь прописано у функції - вкажіть де саме

2022-11-11 13:48 UTC, kostyantynHrytsyuk commented on game_1.py
> +        if if_letter_in_alphabet==True:
Ця перевірка непотрібна тут
if_letter_in_alphabet це вже булеве значення

2022-11-11 13:48 UTC, kostyantynHrytsyuk commented on game_1.py
> +            new_new_lst=''.join(new_lst)
new_new_lst - це не найкраща назва для змінної

2022-11-11 14:49 UTC, yarkapetruniv requested changes
Не потрібно додавати else після return.

2022-11-11 18:18 UTC, Vitaliypn approved these changes

2022-11-11 19:46 UTC, kostyantynHrytsyuk requested changes

2022-11-11 19:46 UTC, kostyantynHrytsyuk commented on game_1.py
> +        if if_letter_in_alphabet==True:
У вас тут далі ця непотрібна перевірка

Заберіть == True, це ніяк не вплине на виконання коду

2022-11-11 20:06 UTC, yarkapetruniv approved these changes

2022-11-12 09:42 UTC, kostyantynHrytsyuk approved these changes
Тепер все добре

Натисність всюди "Resolve conversation" і робіть merge

2022-11-12 10:38 UTC, merged